# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bandsman' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bandsman

  pod 'AFNetworking', '~> 3.2.1'
  pod 'YYKit', '~> 1.0.9'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MJRefresh', '~> 3.1.15.7'
  pod 'Masonry', '~> 1.1.0'
  pod 'Mantle', '~> 2.1.0'
  pod 'SDWebImage'
  pod 'SVProgressHUD'

  # 友盟
  pod 'UMCCommon'
  pod 'UMCCommonLog'
  pod 'UMCSecurityPlugins'
  pod 'UMCAnalytics'

  # 数据转换
  pod 'MJExtension', '=3.0.15.1'

  # 防止崩溃
  pod 'AvoidCrash', '= 2.5.2'



  target 'BandsmanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BandsmanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
